# Generated by Django 2.1.1 on 2019-02-19 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('punchline', models.TextField()),
                ('type_text', models.CharField(max_length=20)),
                ('imageUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='GameMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('nick', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('moreInfo', models.TextField()),
                ('author', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Average', 'Average'), ('Veteran', 'Veteran')], default='Beginner', max_length=10)),
                ('maximumPlayers', models.IntegerField()),
                ('minimumPlayers', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.Event')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.Game')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscriptions.GameMaster')),
            ],
        ),
    ]
